volumes:
  db_data:

services:
  db:
    image: postgres:15
    container_name: the-brink-db
    environment:
      POSTGRES_DB:       brinkdatabase
      POSTGRES_USER:     PitchSuite
      POSTGRES_PASSWORD: theBrink0628
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    ports:
      - "5433:5432"

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: the-brink-backend
    environment:
      DATABASE_URL: postgres://PitchSuite:theBrink0628@db:5432/brinkdatabase
      EMAIL_USER:  ${EMAIL_USER}
      EMAIL_PASS:  ${EMAIL_PASS}
    depends_on:
      - db
    ports:
      - "3001:3001"

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: the-brink-frontend
    depends_on:
      - backend
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    ports:
      - "80:80"
      - "443:443"

