services:
  frontend:
    container_name: react
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    command: npm start
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      FAST_REFRESH: "false"
      NODE_OPTIONS: "--openssl-legacy-provider"
      HOST: "0.0.0.0"
      DANGEROUSLY_DISABLE_HOST_CHECK: "true"
    ports:
      - "3000:3000"

  backend:
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    command: node server.js
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      DATABASE_URL: postgres://PitchSuite:theBrink0628@db:5432/brinkdatabase
      EMAIL_USER: ${EMAIL_USER}
      EMAIL_PASS: ${EMAIL_PASS}
    depends_on:
      - db
    ports:
      - "3001:3001" 
  db:
    container_name: postgres
    image: postgres:15
    environment:
      POSTGRES_DB: brinkdatabase
      POSTGRES_USER: PitchSuite
      POSTGRES_PASSWORD: theBrink0628
    ports:
      - "5433:5432"
    volumes:
      - ./db:/docker-entrypoint-initdb.d
      
volumes:
  db_data:
