services:
  nginx:
    image: nginx:stable-alpine
    container_name: the-brink-proxy
    restart: unless-stopped
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - frontend
      - backend
    networks:
      - the-brink-net

  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    command: npm start
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      FAST_REFRESH: "false"
      NODE_OPTIONS: "--openssl-legacy-provider"
      HOST: "0.0.0.0"
      DANGEROUSLY_DISABLE_HOST_CHECK: "true"
    expose:
      - "3000"
    networks:
      - the-brink-net

  backend:
    container_name: backend
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    command: node server.js
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      DATABASE_URL: postgres://PitchSuite:theBrink0628@db:5432/brinkdatabase
      EMAIL_USER: ${EMAIL_USER}
      EMAIL_PASS: ${EMAIL_PASS}
    expose:
      - "3001"
    networks:
      - the-brink-net

  db:
    container_name: postgres
    image: postgres:15
    environment:
      POSTGRES_DB: brinkdatabase
      POSTGRES_USER: PitchSuite
      POSTGRES_PASSWORD: theBrink0628
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db:/docker-entrypoint-initdb.d
    networks:
      - the-brink-net

volumes:
  db_data:

networks:
  the-brink-net:
    driver: bridge

