services:
  frontend:
    container_name: react
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"

  db:
    container_name: postgres
    image: postgres:15
    environment:
      POSTGRES_USER: PitchSuite
      POSTGRES_PASSWORD: theBrink0628
      POSTGRES_DB: brinkdatabase
    ports:
      - "5432:5432"
 
