services:
  frontend:
    container_name: react
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"

  db:
    container_name: postgres
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
 
