name: Lint Code Base

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read
  checks: write
  actions: read
  pull-requests: write # Needed for PR annotations

jobs:
  run-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Required for full history

      - name: Lint Code Base
        uses: github/super-linter@v4
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: "main"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LINTER_RULES_PATH: "."
          TEXTLINT_CONFIG_FILE: ".textlintrc"
          FILTER_REGEX_EXCLUDE: "node_modules/|build/|public/|.git/|.github/|.vscode/|.env|Dockerfile|docker-compose.yml|package-lock.json|private_key|private_key.pub"
